// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRBpt-Fv1XUs3CgjUV0LC0mbxFXi2fKM',
    appId: '1:582356925682:web:fb61de53994a8c98e9646b',
    messagingSenderId: '582356925682',
    projectId: 'mynotes-moyarishka',
    authDomain: 'mynotes-moyarishka.firebaseapp.com',
    storageBucket: 'mynotes-moyarishka.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUymePu0vzzDtpXStU89xRzctm6u2sX7M',
    appId: '1:582356925682:android:c4fd95feb1037ea9e9646b',
    messagingSenderId: '582356925682',
    projectId: 'mynotes-moyarishka',
    storageBucket: 'mynotes-moyarishka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yk0LJZ1n7SdARTNwCKZ30g-gvMafpPg',
    appId: '1:582356925682:ios:e95c3184e7118c39e9646b',
    messagingSenderId: '582356925682',
    projectId: 'mynotes-moyarishka',
    storageBucket: 'mynotes-moyarishka.appspot.com',
    iosBundleId: 'com.moyarishka123.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_yk0LJZ1n7SdARTNwCKZ30g-gvMafpPg',
    appId: '1:582356925682:ios:8dac619efa4a65a9e9646b',
    messagingSenderId: '582356925682',
    projectId: 'mynotes-moyarishka',
    storageBucket: 'mynotes-moyarishka.appspot.com',
    iosBundleId: 'com.moyarishka123.mynotes.RunnerTests',
  );
}
